### PR TITLE
#222 Add --tolerate option to remote trim command

### PR DESCRIPTION
**Pull request by vl3**
PR for #222
Adding --tolerate option to remote trim command. 
The usage is as following:
`zold remote trim --tolerate=<errors_to_tolerate>`
When the client does not send **--tolerate**, Remote::TOLERANCE is used instead.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#284](https://github.com/zold-io/zold/issues/284) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#284](https://github.com/zold-io/zold/issues/284) is assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1742017429); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/284#issuecomment-399728158))

@yegor256 This pull request [#284](https://github.com/zold-io/zold/issues/284) is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1750462520); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#284](https://github.com/zold-io/zold/issues/284) is now out of scope

**Pull request merged**
