### PR TITLE
Issue #385 Move Upgrade code from zold to upgrades.

### PR DESCRIPTION
**Pull request by SergeyKutsko**
https://github.com/zold-io/zold/issues/385

According to issue  moved code from bin/zold.rb to lib/zold/upgrades.rb

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#592](https://github.com/zold-io/zold/issues/592) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#592](https://github.com/zold-io/zold/issues/592) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/44990877-0b95-4384-955b-0c5cce17dad1); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by SergeyKutsko** [comment]
@emilianodellacasa, fixed thx.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#592](https://github.com/zold-io/zold/issues/592) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by emilianodellacasa** [comment]
@ypshenychka Confirmed, but I found different problems in the QA realm. As you see, I am a fast lerner! :-)

**Comment by ypshenychka** [comment]
@emilianodellacasa That's really great and I'm thankful for that :) Unfortunately, quality should be bad here because of no issues during code review, so no bonus for your efforts...

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by emilianodellacasa** [comment]
@ypshenychka Sorry, but [here](https://github.com/zold-io/zold-score/pull/13#issuecomment-442515038) you said ticket performer can suggest modifications based on QA rules, and receive a bonus for it. I don't get it.

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by ypshenychka** [comment]
@emilianodellacasa Looks like we've got a misunderstanding here. What I meant is a quality mark "good", that goes as [bonus](http://www.zerocracy.com/policy.html#31) if all quality rules are in place. Otherwise it would be "acceptable".

But in case no issues are found while code review - quality mark is 'bad'.
>The quality of a job is “bad” if any of the following happens (these violations we can’t forgive):
> - The code reviewer didn’t find any issues in the source code changes of a pull request and just accepted it;

**Comment by ypshenychka** [comment]
@emilianodellacasa That's how the current rule states. And there's no way to pay you a bonus along with "bad" quality mark. 
But it would be a nice thing to have, you know... Probably you could create a ticket and we see how can it be implemented? In case there's a violation we can't forgive, but person applied some efforts to make ticket conforming to QA rules.

**Comment by SergeyKutsko** [comment]
@ypshenychka Will i receive bonus now?

**Comment by SergeyKutsko** [comment]
Quality is low, no payment, see §31

**Comment by ypshenychka** [comment]
@SergeyKutsko Please address your previous message to someone.
In scope of PR - code reviewer is paid\not paid. Your payment will be made in scope of original issue #385 once you respond to my comment in it.

**Pull request merged**
