### PR TITLE
Updated INSTALL.md to include firewall configuration for PFSense

### PR DESCRIPTION
**Pull request by postables**
Nothing too major, just updated INSTALL.md with how to configure your pfsense firewall so that it can properly forward traffic to your ZOLD node.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#407](https://github.com/zold-io/zold/issues/407) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@postables thanks!

**Comment by 0crat** [comment]
This pull request [#407](https://github.com/zold-io/zold/issues/407) is assigned to @ledestin[/z](https://www.0crat.com/u/ledestin), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1981026318); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ledestin[/z](https://www.0crat.com/u/ledestin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#407](https://github.com/zold-io/zold/issues/407) is now out of scope

**Comment by ypshenychka** [comment]
@yegor256 Looks like no Code Review was done here and 0crat assigned ticket to QA too quick. Should I proceed with review anyways?

**Comment by yegor256** [comment]
@ypshenychka just make quality bad here

**Comment by ypshenychka** [comment]
@yegor256 ok, thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request merged**
