### PR TITLE
remove unused test from test merge

### PR DESCRIPTION
**Pull request by strogiyotec**
https://github.com/zold-io/zold/issues/733

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#734](https://github.com/zold-io/zold/issues/734) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#734](https://github.com/zold-io/zold/issues/734); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@strogiyotec thanks

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#734` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#734](https://github.com/zold-io/zold/issues/734) is now out of scope

**Pull request merged**
