### PR TITLE
[#574] Fixes problem with libcurl in appveyor by migrating from patron to typheous 

### LINKED ISSUE #574: Appveyor build is broken: libcurl is not found
https://ci.appveyor.com/project/yegor256/zold-jhx6b/builds/20528112/job/y8x1po291wrq3d4v

screen shot 2018-11-26 at 17 14 37

### PR DESCRIPTION
**Pull request by dapi**
I migrate from `patron` to `typheous`. There are next reasons:

1) fixes #574 libcurl problem with `appveyor`.  `patron` with `curb` with has broken windows support
2) `typheous` uses `ethon` to bind libcurl though `ffi` (this is better solution, I use it for several years)
3) `typheous` is much dry than `patron`

There are still many errors in appveyour. Problem with event machine fixed by this PR - https://github.com/dapi/zold/pull/9/files

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#582](https://github.com/zold-io/zold/issues/582) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/520d7be5-5a3d-443f-a428-9cb47738cec6); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@dapi @yegor256 I cannot see any major issue in this PR, we can merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#582](https://github.com/zold-io/zold/issues/582) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issue were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by emilianodellacasa** [comment]
@ypshenychka Confirmed

**Comment by ypshenychka** [comment]
@emilianodellacasa thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by dapi** [comment]
@ypshenychka please five more information about quality

**Comment by ypshenychka** [comment]
@dapi Can you elaborate more on your comment? Probably it ought to be in another pull request thread.

**Pull request merged**
