### PR TITLE
#444: Correct pass header to net.http

### PR DESCRIPTION
**Pull request by DronMDF**
To avoid duplication of Content-Length

Old way cause duplication.
If you set debug output to $stdout, you can see it:
```
<- "PUT /wallet/0000000000000000 HTTP/1.1\r\nUser-Agent: Zold 0.0.0\r\nConnection: close\r\nAccept-Encoding: gzip\r\nX-Zold-Version: 0.0.0\r\nX-Zold-Protocol: 2\r\nX-Zold-Network: test\r\nContent-Type: text/plain\r\nContent-Length: 1535\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: 138.197.140.42:4096\r\nContent-Length: 1535\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n"
```

nginx reject this request.
The new version works well.

I'm not ruby developer and not known where is difference between : and =>...
May be : should be declared inside curly braces?

And I don't know how test it. Help me please.

### CODE REVIEW

**Comment by 0crat** [comment]
@DronMDF this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@DronMDF looks good, but there are some merge conflicts, can you please resolve them?

**Comment by DronMDF** [comment]
@yegor256 I'm done.

How my 2 line patch can decrease coverage in 25 files? 8-()

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#477` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
