### PR TITLE
#105 rewrite score calculation in C

### PR DESCRIPTION
**Pull request by oltdaniel**
## Things solved
The score calculation has been rewritten in C and divided up to 3 Processes, managed by Ruby. This pull request however doesn't include the updated for the node farm, interface, etc., these things will be solved in further pull requests.

## Next tasks
- [ ] Update node farm score usage
- [ ] Update interface for `--cores=` option
- [ ] Update build instructions for `clang` installation **very important**
- [ ] Test cases for the C extension
- [ ] Windows support _(low priority, ticket will be submitted)_

> Links to issues for each task will be added

## Note
The `ScoreExt` module lives under the main module `Zold` and can be found in `lib/zold/ext/score.rb`.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#335](https://github.com/zold-io/zold/issues/335) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#335](https://github.com/zold-io/zold/issues/335) is assigned to @ledestin[/z](https://www.0crat.com/u/ledestin), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1841524521); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by oltdaniel** [comment]
@yegor256 @ledestin Build fails due to missing clang installation.

**Comment by oltdaniel** [comment]
Failed due to timeouts. These are propbaly caused by the 3 processes, which block the actual ruby node front process.

**Comment by ledestin** [comment]
@0crat refuse

**Comment by oltdaniel** [comment]
@ledestin Will close this, cause the front crashes without any error message after the first request.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ledestin[/z](https://www.0crat.com/u/ledestin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#335](https://github.com/zold-io/zold/issues/335) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@oltdaniel According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zold-io/zold/pull/335#issuecomment-402242328) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@oltdaniel According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Please confirm you'll follow this rule next time.

**Comment by ypshenychka** [comment]
@oltdaniel According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add link to original issue into description.

**Comment by ypshenychka** [comment]
@oltdaniel ping

**Comment by ypshenychka** [comment]
@oltdaniel waiting on your corrections and confirmation

**Comment by oltdaniel** [comment]
@ypshenychka I have an unknown issue with the node in my implementation I am not able to correct currently. They will stop after a random time without throwing any errors. The actual scores however are calculated correctly.

**Comment by ypshenychka** [comment]
@oltdaniel I see. But please make corrections as I asked in my comments above (about addressee and link to issue). And also confirm you'll follow the rule about commit messages.

**Comment by ypshenychka** [comment]
@oltdaniel ping

**Comment by oltdaniel** [comment]
@oltdaniel I confirm

**Comment by ypshenychka** [comment]
@oltdaniel Please correct your message as I mentioned in this [remark](https://github.com/zold-io/zold/pull/335#issuecomment-402441091)

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @ledestin[/z](https://www.0crat.com/u/ledestin)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by oltdaniel** [comment]
@ypshenychka Will follow the commit message rule next time.

**Comment by ypshenychka** [comment]
@oltdaniel thanks

**Comment by yegor256** [comment]
@oltdaniel let's try again here: https://github.com/zold-io/zold-score/issues/2

**Pull request closed without merging**
