### PR TITLE
#211 unerror for remotes added

### LINKED ISSUE #211: Remotes::Remote must un-error on success
At the moment we call `error` if something happens with the remote node. Let's do `unerror()` if there are no accidents/exceptions. Also, that `unerror` must not lower the number below zero.

### PR DESCRIPTION
**Pull request by oltdaniel**
Fixed #211 

I added the `Remotes#unerror` method that will decrement the error counter for a given remote.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#434](https://github.com/zold-io/zold/issues/434) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@oltdaniel the code looks good, but I can't merge manually. Please, solve the conflict and I will ask Rultor to merge

**Comment by oltdaniel** [comment]
@yegor256 Solved stupid merge conflicts. Newly added lines vs nothing from master.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@oltdaniel did you test it locally?

**Comment by oltdaniel** [comment]
@yegor256 I am sorry. Forgot to remove the `do`.

**Comment by oltdaniel** [comment]
@yegor256 ready. Travis fails due to https://github.com/zold-io/zold/issues/419

**Comment by oltdaniel** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
This pull request [#434](https://github.com/zold-io/zold/issues/434) is assigned to @hl-a-k[/z](https://www.0crat.com/u/hl-a-k), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/2361766015); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by hl-a-k** [comment]
@yegor256 , I lost role REV because my reputation is +0(below + 128);  according the policy, I can't be a reviewer.  Can I perform review anyway? Or assign the task to someone else?

**Comment by oltdaniel** [comment]
@yegor256 Will need to rewrite cause of some changes done.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @hl-a-k[/z](https://www.0crat.com/u/hl-a-k), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#434](https://github.com/zold-io/zold/issues/434) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@hl-a-k According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@hl-a-k ping

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
