### PR TITLE
Issue #346 - Reviewed development dependencies

### PR DESCRIPTION
**Pull request by emilianodellacasa**
For issue #346, I reviewed all dependencies in zold.gemspec to avoid installing unnecessary gems for a runtime environment.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#641](https://github.com/zold-io/zold/issues/641) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#641](https://github.com/zold-io/zold/issues/641); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#641](https://github.com/zold-io/zold/issues/641); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@emilianodellacasa this won't work in Heroku, because they run `rake` over there and Rubocop is required. Try to run `bundle install --without=development` and then run `rake`. You will see the problem.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#641](https://github.com/zold-io/zold/issues/641); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#641](https://github.com/zold-io/zold/issues/641); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@emilianodellacasa it's fixed in #662

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#641` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#641](https://github.com/zold-io/zold/issues/641) is now out of scope

**Pull request closed without merging**
