### PR TITLE
#105: C++ score calculation module

### PR DESCRIPTION
**Pull request by DronMDF**
Module calculate next nonce(suffix) value in parallel.
All available CPU are used.

It is not necessary to build threads pools on top.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#186](https://github.com/zold-io/zold/issues/186) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#186](https://github.com/zold-io/zold/issues/186) is assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1591943987); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by DronMDF** [comment]
@yegor256 One test is very long.
I would like to understand what his exit criteria are. And why did not he work for an hour before?

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@DronMDF can you please add some C++ linter to the build? We need something to check the style/formatting of the C++ code.

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/186#issuecomment-395995398))

@yegor256 This pull request [#186](https://github.com/zold-io/zold/issues/186) is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1602017773); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by DronMDF** [comment]
@yegor256 Very old ubuntu on travis...
The cppcheck may be old.
cpplint will not go, because there is no python.

Let's try it.

**Comment by yegor256** [comment]
@rultor merge

**Comment by DronMDF** [comment]
I think - test not stop calculation threads...
How server stop in tests?

```
Failure:
FrontTest#test_gzip [/home/dron/Projects/zold/test/node/test_front.rb:135]:
Expected HTTP 200 OK: Found 599.
Expected: "200"
  Actual: "599"


bin/rails test home/dron/Projects/zold/test/node/test_front.rb:132

farm-1: best score is 8/6: 2018-06-12T11:53:50Z localhost 45765 NOPREFIX@ffffffffffffffff fMeb3Z tsNciP xJ4W8n fxYcRp RtBwsF 10NcAu RngOYr bNYmUb
```

**Comment by DronMDF** [comment]
@yegor256 I can simplify commit, drop inner threads.
Maybe the build will be more stable?
The speed will increase, and the farm already has threads, we will look at the utilization.

**Comment by yegor256** [comment]
@DronMDF please, submit all your concerns/ideas as separate tickets

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@DronMDF it seems that there is something wrong in your branch

**Comment by oltdaniel** [comment]
@yegor256 @DronMDF Would recommend `ffi`. This requires a custom rake task that calls clang, but it would give us a better performance. [Comparison](https://www.amberbit.com/blog/2014/6/12/calling-c-cpp-from-ruby/#so-which-one-to-use)

**Comment by DronMDF** [comment]
@yegor256 Close this PR too.

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#186](https://github.com/zold-io/zold/issues/186) is now out of scope

**Pull request closed without merging**
