### PR TITLE
#61:  calculate wallet "age" 

### PR DESCRIPTION
**Pull request by sandiks**
calculate wallet "age" as a difference between the oldest transaction and the most recent one

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#247](https://github.com/zold-io/zold/issues/247) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#247](https://github.com/zold-io/zold/issues/247) is assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1671342950); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by yegor256** [comment]
@rultor merge

**Comment by oltdaniel** [comment]
Do `/ (60*60)` because the current return time is in minutes. And since this number is different, update the tax calculations, because the test cases are done for minutes.

@yegor256 @sandisk

**Comment by sandiks** [comment]
fixed

**Comment by sandiks** [comment]
is good decision id i use such trick Math.abs(age-3600)<2?

**Comment by oltdaniel** [comment]
@sandisk As i mentioned above, the tax calculations fail because of the new age [here](https://travis-ci.org/zold-io/zold/builds/394947005#L841). The new number is in hours and will so on be lower than expected. The test cases and forumla need to be updated.

**Comment by sandiks** [comment]
where can i find tax caluclation?

**Comment by oltdaniel** [comment]
@sandiks Take a look (here)[
https://github.com/zold-io/zold/blob/master/test/test_tax.rb#L50]. The
numbers need to be recalculated. Maybe ask @yegor256 to help in order to be
sure.

Nik Os <notifications@github.com> schrieb am Do., 21. Juni 2018, 12:38:

**Comment by sandiks** [comment]
if we have one trans, whats is the wallet age?

**Comment by oltdaniel** [comment]
@sandisk Should be 0 as @yegor256 mentioned during my work

**Comment by sandiks** [comment]
check it

**Comment by oltdaniel** [comment]
@sandisk Looks good so far. But [this](https://github.com/zold-io/zold/blob/master/test/node/test_emission.rb#L32) still fails cause of the zero age on a single transaction.

**Comment by 0crat** [comment]
@ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by sandiks** [comment]
test passed

# Running:

.Year: 1, Quota: 0.0%, Limit: 0.00ZLD
Year: 2, Quota: 0.0%, Limit: 0.00ZLD
Year: 3, Quota: 0.0%, Limit: 0.00ZLD
Year: 4, Quota: 0.0%, Limit: 0.00ZLD
Year: 5, Quota: 0.0%, Limit: 0.00ZLD
Year: 6, Quota: 0.0%, Limit: 0.00ZLD
Year: 7, Quota: 0.0%, Limit: 0.00ZLD
Year: 8, Quota: 0.0%, Limit: 0.00ZLD
Year: 9, Quota: 0.0%, Limit: 0.00ZLD
Year: 10, Quota: 0.0%, Limit: 0.00ZLD
.....

Finished in 0.104438s, 57.4506 runs/s, 0.0000 assertions/s.
6 runs, 0 assertions, 0 failures, 0 errors, 0 skips

**Comment by oltdaniel** [comment]
@sandisk Test passed because there is no check if it is zero. Orginially it should output the emission described in the paper.

**Comment by sandiks** [comment]
open the next task to fix or i need to do that?

**Comment by oltdaniel** [comment]
@sandisk This task includes this kind of work. You did something, where the test cases don't work. The only thing is, you need to duplicate the transactions in the emission test.

**Comment by oltdaniel** [comment]
@sandiks That's it. Ok from me @yegor256

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@sandiks unfortunately, your branch is still not mergeable

**Comment by oltdaniel** [comment]
@sandisk Somehow the test complaims about the lines in the wallet. It raises an error on `<= 4` lines. Run the test and check the wallet content that will be the followed line in your test, after [this one](https://travis-ci.org/zold-io/zold/builds/395506503#L1745) by running the `$ rake test`.

**Comment by 0crat** [comment]
The user @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets) resigned from [#247](https://github.com/zold-io/zold/issues/247), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets)

**Comment by 0crat** [comment]
This pull request [#247](https://github.com/zold-io/zold/issues/247) is assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1771357459); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@sandiks just now, I saw that @0crat remove the issue #61 from you. In the future, ask @0crat to [wait](https://www.zerocracy.com/policy.html#9).

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zold-io/zold/issues/247#issuecomment-402540101); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by sandiks** [comment]
I'm not working on a project now

**Comment by pbenety** [comment]
@yegor256 please close this PR. It is not good to merge.

**Comment by oltdaniel** [comment]
@sandiks Try a new pull request with no broken tests and only a few commits. Check before commit with `rake`.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#247](https://github.com/zold-io/zold/issues/247) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@pbenety According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by pbenety** [comment]
@ypshenychka I confirm.

**Comment by ypshenychka** [comment]
@pbenety thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
