### PR TITLE
Issue #394 - Removing old puzzle and adding a new one

### PR DESCRIPTION
**Pull request by emilianodellacasa**
In this PR for isse #394 I just modified the puzzle comment to close the old one and open a new one to proceed with the refactoring of dry-types

### CODE REVIEW

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by emilianodellacasa** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#417` is not assigned, can't get performer

**Pull request merged**
