### PR TITLE
Issue #298: if remote is missing avoid throwing an exception

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Now when a remote in missing for a valid reason (ex. unreachable at the moment), no exception is thrown - just logged. Added steps to test it and checked that no previous test is broken

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#309](https://github.com/zold-io/zold/issues/309) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#309](https://github.com/zold-io/zold/issues/309) is assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1791334946); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@pbenety Thanks. What do you mean that this PR is fixing two issues? Sorry I don't get it

**Comment by pbenety** [comment]
@emilianodellacasa you're fixing the #297 and #298 in this PR.

**Comment by emilianodellacasa** [comment]
Ok, shall I close and open another one with just the single fix?

**Comment by pbenety** [comment]
@emilianodellacasa yes, create a new branch only with #298 fix and create a new PR.

**Comment by emilianodellacasa** [comment]
Ok; i have opened another one, closing this

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#309](https://github.com/zold-io/zold/issues/309) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your messages ([here](https://github.com/zold-io/zold/pull/309#issuecomment-401381792) and [here](https://github.com/zold-io/zold/pull/309#issuecomment-401397547)) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add link to original issue into PR's description.

**Comment by ypshenychka** [comment]
@pbenety According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@emilianodellacasa @pbenety ping

**Comment by pbenety** [comment]
@ypshenychka I found a critical issue and asked @emilianodellacasa to open a new one #312.

**Comment by pbenety** [comment]
@yegor256 I rejected this PR. Do you acknowledge it?

**Comment by ypshenychka** [comment]
@pbenety I see. Thank you for explanation. Waiting for @emilianodellacasa to make appropriate corrections then.

**Comment by yegor256** [comment]
@pbenety yes, I agree with your decision. Fixing two problems in one PR is a bad idea.

**Comment by ypshenychka** [comment]
@emilianodellacasa ping

**Comment by emilianodellacasa** [comment]
@ypshenychka Fixed the PR description adding the link to the issue and corrected the two comments by stating the addressee

**Comment by ypshenychka** [comment]
@emilianodellacasa Thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
