### PR TITLE
#676: a workaround for the aggressive file system utilisation documented.

### PR DESCRIPTION
**Pull request by denis-konovalyenko**
A workaround for the issue #676 has been documented.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#714](https://github.com/zold-io/zold/issues/714) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#714](https://github.com/zold-io/zold/issues/714); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@denis-konovalyenko thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#714` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#714](https://github.com/zold-io/zold/issues/714) is now out of scope

**Pull request merged**
