### PR TITLE
[140] PDD Add Nginx dependency

### PR DESCRIPTION
**Pull request by SergeyKutsko**

### CODE REVIEW

**Comment by 0crat** [comment]
@SergeyKutsko this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@SergeyKutsko where do you want us to add this? We don't have nginx in our Ruby gem :)

**Comment by SergeyKutsko** [comment]
@yegor256 I need nginx to be shipped with zold or use system nginx  or install if no nginx, it is not possible to handle https and http with Sinatra and Thin without nginx

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#614` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
