### PR TITLE
Issue #356 - Adding guard for incremental testing

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Solving issue #356

I added guard to Zold gemspec, for the purpose of incremental testing. To use it, just type in the command line:

`bundle exec guard`

This way, whenever a file is modified, guard will run the related test, without running the whole suite (that could take a while, as all know).

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#655](https://github.com/zold-io/zold/issues/655) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#655](https://github.com/zold-io/zold/issues/655); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#655` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#655](https://github.com/zold-io/zold/issues/655) is now out of scope

**Pull request merged**
