### PR TITLE
#211 implement unerror for remotes

### PR DESCRIPTION
**Pull request by oltdaniel**
Fixes https://github.com/zold-io/zold/issues/211

## Notes
Implement `Zold::Remotes#unerror` to reduce error counter.

### CODE REVIEW

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by oltdaniel** [comment]
@yegor256 ping for review

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#476` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
