### PR TITLE
Using RSA instead of PGP

### PR DESCRIPTION
**Pull request by holly-fingers**
Invoice of 1ZLD should be paid to da8402c488c1def0

### CODE REVIEW

**Comment by 0crat** [comment]
@holly-fingers[/z](https://www.0crat.com/u/holly-fingers) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#293` is not assigned, can't get performer

**Comment by yegor256** [comment]
@holly-fingers thanks! paid: http://b2.zold.io:4096/wallet/912ecc24b32dbe74.txt (wait for update)

**Pull request merged**
