### PR TITLE
Issue #560 - Fixed problem with test

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Issue #560 

I modified the test by breaking the loop when a "\r\n" is returned

### CODE REVIEW

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@emilianodellacasa I believe you forgot to remove the puzzle

**Comment by emilianodellacasa** [comment]
@yegor256 You are right, now I removed it

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#637` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
