### PR TITLE
#86 GZIP

### PR DESCRIPTION
**Pull request by oltdaniel**

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#177](https://github.com/zold-io/zold/issues/177) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#177](https://github.com/zold-io/zold/issues/177) is assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1591057805); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by IlyaUmanets** [comment]
@oltdaniel, please fix tests

**Comment by oltdaniel** [comment]
@yegor256 @IlyaUmanets Local rake test with 0 failures

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#177](https://github.com/zold-io/zold/issues/177) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@oltdaniel According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request title explains the problem it is fixing;
Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add more details to the title and description of the pull request along with link to original issue.

**Comment by ypshenychka** [comment]
@IlyaUmanets According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@oltdaniel @IlyaUmanets ping

**Comment by ypshenychka** [comment]
@oltdaniel @IlyaUmanets Please consider my above remarks so I could proceed with QA review.

**Comment by ypshenychka** [comment]
@oltdaniel @IlyaUmanets Ping

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
