### PR TITLE
#327: remove redundant puzzle

### PR DESCRIPTION
**Pull request by ledestin**
I forgot to remove the puzzle in https://github.com/zold-io/zold/pull/351

### CODE REVIEW

**Comment by 0crat** [comment]
@ledestin[/z](https://www.0crat.com/u/ledestin) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#373` is not assigned, can't get performer

**Pull request merged**
