### PR TITLE
Implemented Issue 305

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Just a couple of lines modified, all tests green

### CODE REVIEW

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#311` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by emilianodellacasa** [comment]
@yegor256 Is there something missing on this PR to proceed with closing the issue?

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@emilianodellacasa the PR is merged, now you should continue in the ticket. This PR is done.

**Pull request merged**
