### PR TITLE
#72: substract the prefix from full path if its equal

### PR DESCRIPTION
**Pull request by sandiks**
I have added require 'pathname' and used relative_path_from method to modify path

### CODE REVIEW

**Comment by 0crat** [comment]
@sandiks[/z](https://www.0crat.com/u/sandiks) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@sandiks looks good. How about a unit test? How do you know the code works?

**Comment by sandiks** [comment]
i have added test

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@sandiks see the problems above. Before submitting your changes, make sure the build is clean by running `rake`.

**Comment by sandiks** [comment]
what does 'fake-node.local' mean?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@sandiks still some problems with code formatting

**Comment by sandiks** [comment]
cant imagine where is problem

**Comment by sandiks** [comment]
fixed

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@sandiks thanks! appreciate your help!

**Pull request merged**
