### PR TITLE
Issue #231 - Adding openssl header to build

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Opening a new PR for #231, I am adding the openssl header to bundle.

Please wait for my confirmation before merging.

### CODE REVIEW

**Comment by emilianodellacasa** [comment]
@yegor256 You can merge now, appveor is failing because some tests are not passing because of the windows environment, I am creating an issue for it.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#443` is not assigned, can't get performer

**Pull request merged**
