### PR TITLE
#514 improve total_wallets count

### PR DESCRIPTION
**Pull request by vl3**
#514 
I added **count** method to _Wallets_ and _TreeWallets_.  _Wallets#count_ performs a tradditional count of any file in its directory while _TreeWallets#count_ traverse through a directory hierarchy and performs a count.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#617](https://github.com/zold-io/zold/issues/617) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#617](https://github.com/zold-io/zold/issues/617) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/3a7a46c9-49be-4a18-9039-d5e0ea65dd64); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@vl3 please see my comments

**Comment by vl3** [comment]
@emilianodellacasa Can't see your comments.  Where are they ?

**Comment by emilianodellacasa** [comment]
@vl3 you should see my comments in the "Files changed" section. Also, plase add the code of the issue in the the PR description (that is, your first comment of the PR)

**Comment by vl3** [comment]
@emilianodellacasa Can't see anything, are you sure that the comments were submitted ?

**Comment by vl3** [comment]
@emilianodellacasa comments applied

**Comment by emilianodellacasa** [comment]
@yegor256 we can merge

**Comment by emilianodellacasa** [comment]
@vl3 thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by ypshenychka** [comment]
@emilianodellacasa According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only two issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by emilianodellacasa** [comment]
@ypshenychka Confirmed

**Pull request merged**
