### PR TITLE
Remove Ruby 2.3 support. Use 2.5.1 as development version

### PR DESCRIPTION
**Pull request by dapi**

### CODE REVIEW

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@dapi thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold#576` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
