### PR TITLE
Issue 548 - Reducing Memory Leaks

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Issue #548

By analyzing the output of MemoryProfiler gem (for 500 http requests)

```
allocated memory by gem
-----------------------------------
 527433328  timeout
 168604294  posix-spawn-0.3.13
  82298729  slop-4.6.2
  56423038  webmock-3.4.2
  49400018  zold/lib
  26489067  other
  22553580  net
  21770850  eventmachine-1.2.7
  19961826  csv
  15579665  futex-0.3.1
```

it is clear that too many `Timeout` objects are allocated, and this increase proportionally with time. Therefore, I removed the `net/http` gem and used `patron`, a wrapper around libcurl that is not using the default `Timeout` ruby gem.

Now the output of MemoryProfiler is

```
allocated memory by gem
-----------------------------------
 168604294  posix-spawn-0.3.13
  82298729  slop-4.6.2
  56981424  webmock-3.4.2
  49782233  zold/lib
  21807082  eventmachine-1.2.7
  19961826  csv
  15579705  futex-0.3.1
   7367405  rubygems
   6454972  patron-0.13.1
   6185143  rack-2.0.6
```

Still we could work on reducing the memory leaks introduced by `posix-spawn` and `slop`, but for the moment let's see how this refactoring impacts the gem.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#551](https://github.com/zold-io/zold/issues/551) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#551](https://github.com/zold-io/zold/issues/551) is assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/dd60753d-c1f5-418b-8237-29600e483ebb); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@emilianodellacasa something is missing?

**Comment by emilianodellacasa** [comment]
@yegor256 apparently the rultor image is missing libcurl, how can we solve? We could install libcurl on the image (if possible), or try another http library that is not using libcurl

**Comment by yegor256** [comment]
@emilianodellacasa just add it to the `.rultor.yml`, into the `install` section

**Comment by emilianodellacasa** [comment]
@yegor256 Ok, I have added the installation command, try merging again please

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#551](https://github.com/zold-io/zold/issues/551) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@emilianodellacasa Since there was no actual code review and you were assigned to your own PR, I have to mark it as "bad". Agree?

**Comment by emilianodellacasa** [comment]
@ypshenychka I guess this is the case

**Comment by ypshenychka** [comment]
@emilianodellacasa thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Pull request merged**
