### PR TITLE
#105: C++ score calculation module (signlethreaded)

### PR DESCRIPTION
**Pull request by DronMDF**
This is singlethreaded version.
This version not utilize all CPU. (ruby gaint lock)
Try to integrate this?

Mining speed is grow.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#223](https://github.com/zold-io/zold/issues/223) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#223](https://github.com/zold-io/zold/issues/223) is assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1651260235); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by DronMDF** [comment]
@yegor256 I think that the work with threads in the application is somehow not very clean...
I see thread.exit, and judging by the descriptions - the call to this method does not guarantee the correct completion of threads ... On good it is necessary to join threads. Perhaps the application spends time in the С++ module and does not respond to any signals?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@DronMDF something is wrong in your branch?

**Comment by DronMDF** [comment]
@yegor256 This is a very primitive module. Where could I be wrong?
How could I provoke it:
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/test20180614-12467-vep1xw/farm
?

**Comment by yegor256** [comment]
@DronMDF I also don't understand... does it work on your local machine?

**Comment by DronMDF** [comment]
@yegor256 No.
I get master and see errors like this:
Error:
TestBonuses#test_pays_bonuses:
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /tmp/test20180618-32153-19tl4iq

...
148 runs, 327 assertions, 0 failures, 1 errors, 2 skips

I have a new ruby-2.5... Why you rollback this change? What's wrong with a new ruby?

I'll try check it on clean env, on rignt ruby.

**Comment by 0crat** [comment]
@ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by DronMDF** [comment]
@yegor256 i give clean env (docker pull ruby:2.3.3)

Tests on **master branch** failed:
156 runs, 338 assertions, 1 failures, 0 errors, 2 skips

I See:
```
Failure:
TestZold#test_all_scripts [/home/zold/test/test_zold.rb:49]:
sigdump.sh.
Expected: 0
  Actual: 65280
```
And many errors.
Where i am wrong?

**Comment by 0crat** [comment]
The user @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets) resigned from [#223](https://github.com/zold-io/zold/issues/223), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets)

**Comment by 0crat** [comment]
This pull request [#223](https://github.com/zold-io/zold/issues/223) is assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1751267018); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @vl3[/z](https://www.0crat.com/u/vl3) resigned from [#223](https://github.com/zold-io/zold/issues/223), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
This pull request [#223](https://github.com/zold-io/zold/issues/223) is assigned to @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1851308883); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@oltdaniel[/z](https://www.0crat.com/u/oltdaniel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by oltdaniel** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@DronMDF what do you think about this?

**Comment by DronMDF** [comment]
@yegor256 Ok, close this PR.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @oltdaniel[/z](https://www.0crat.com/u/oltdaniel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#223](https://github.com/zold-io/zold/issues/223) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@DronMDF According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Pull request description explains the solution proposed and contains a link to the original ticket it is related to

Please add link to issue into description.

**Comment by ypshenychka** [comment]
@oltdaniel According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only one issue was found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@DronMDF ping

**Comment by ypshenychka** [comment]
@oltdaniel ping

**Comment by DronMDF** [comment]
@ypshenychka This PR is closed...

Link in the title are not enough?

**Comment by ypshenychka** [comment]
@DronMDF No, it's not. Link in title is not a 'must have'. But it should be necessary in description.

**Comment by DronMDF** [comment]
@ypshenychka Ok, sorry.

**Comment by HarryR** [comment]
@DronMDF I feel sorry for you man, you're getting caught up in their silly bureaucracy where jumping through the autism hoops is worth more than having good code.

Forget about this project, it's not worth spending your time on, lol 64bit ids... they reject a CPU miner, so many other vulns, written in Ruby! *laugh*

**Comment by HarryR** [comment]
also @DronMDF - I really respect you making a CPU miner for this, at least somebody is trying... 

There are a number of things you could improve with the CPU miner.

 1. `index_core` uses string concatenation in every loop, not a static buffer
 2. `create_nonce` is slooowww... Why not just re-cast the last 8 bytes as a `uint64_t` and increment that.
 3. Why re-compute whole `SHA256` round when you can do a single update with the prefix, then do an `update` with the `nonce`, then `memcpy` the digest state from the 'prefix' state

**Comment by HarryR** [comment]
None of the core devs here would know an original idea if it came and smacked them in the face, but here they are re-inventing the wheel and autisming out on t'internets, in Ruby of all languages.

**Comment by HarryR** [comment]
Raiblocks did this first.

Zold is just doing it again, poorly...

Lolloololoolllool

**Comment by DronMDF** [comment]
@HarryR Thank's.

There are many things that can be made even more optimized.
create_nonce for beauty. :) I can not see how incredible hex digits are stuffed into the score.
But this is definitely overenginiaring in this case.

String concatenations and cumulative update not much affect the speed of generating new hashes.
I did not want to fall and go to С. :)

**Comment by HarryR** [comment]
> String concatenations and cumulative update not much affect the speed of generating new hashes.
I did not want to fall and go to С. :)

Annndddd that kind of thinking is how you get out-mined by a Raspberry Pi, at which point the whole notion of the 'score' from the whitepaper becomes a way to easily pwn the entire network and cause chaos.

Been there, done that...

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by yegor256** [comment]
@DronMDF @oltdaniel let's try again here: https://github.com/zold-io/zold-score/issues/2

**Pull request closed without merging**
