### PR TITLE
#86 Gzip all traffic

### PR DESCRIPTION
**Pull request by oltdaniel**
- #86 GZIP all traffic
- Dynamic ruby version for Gemfile

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#151](https://github.com/zold-io/zold/issues/151) is now in scope, role is `REV`

**Comment by oltdaniel** [comment]
@yegor256 Will merge the upstreams correctly next time without using an extra commit and GitHub

**Comment by 0crat** [comment]
This pull request [#151](https://github.com/zold-io/zold/issues/151) is assigned to @ilyaumanets[/z](https://www.0crat.com/u/ilyaumanets), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1561935830); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by oltdaniel** [comment]
Build fail has nothing to do with the pull request.

**Comment by yegor256** [comment]
@oltdaniel don't hesitate to submit a ticket about build failure

**Comment by oltdaniel** [comment]
@yegor256 Already did https://github.com/zold-io/zold/issues/149

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zold-io/zold/issues/151#issuecomment-395348676))

@yegor256 This pull request [#151](https://github.com/zold-io/zold/issues/151) is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1580912609); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@oltdaniel seems to be a bug in your branch?

**Comment by yegor256** [comment]
@rultor merge

**Comment by oltdaniel** [comment]
@yegor256 GZip actually worked good, but looks loke some issues in reading and decompressing the request.

**Comment by yegor256** [comment]
@oltdaniel seems to be so. Please, don't forget to merge the `master` into your branch

**Comment by oltdaniel** [comment]
@yegor256 Will clean up and make a new one with the current version. To many changes made in the master.

**Comment by 0crat** [comment]
Order was finished: +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#151](https://github.com/zold-io/zold/issues/151) is now out of scope

**Pull request closed without merging**
