### PR TITLE
Issue #298 - when remote is unavailable fail silently

### PR DESCRIPTION
**Pull request by emilianodellacasa**
Issue #298 - When the remote is not temporaly available it fails silently and send a message to the log instead of throwing an exception

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#312](https://github.com/zold-io/zold/issues/312) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#312](https://github.com/zold-io/zold/issues/312) is assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1801606377); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@pbenety It's all green now

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@emilianodellacasa I don't think this solves anything. Did you manage to reproduce the problem with test? The stubbing thing you use reproduces the situation which doesn't happen in real life. What really happens is a concurrency issue between threads.

**Comment by emilianodellacasa** [comment]
@yegor256 Honestly, I don't see the point. The purpose of the issue was to avoid the code to throw an exception and just leaving a log, this is what the code does and the test I have written clearly covers the case.

Creating a test dealing with thread concurrency is not easy task (just take into account that several tests right now fail from time to time because of thread concurrency), and could be really unstable.

However, if you feel that the test I made it is not enough I can create another one _trying_ to reproduce the thread concurrency issue, but IMHO stubbing the non-existence of the remote in the list should be enough to cover it.

Just let me know what you prefer.

**Comment by yegor256** [comment]
@emilianodellacasa but this is not what happens in production! Moreover, the situation you are reproducing now will never happen in production. If the list of remotes doesn't have an item, it won't raise an exception. If it has an item, the error will be recorded correctly. No matter how many times you check for `exists?` -- the exception will happen anyway, from another thread. It's a concurrency issue, not a logical mistake of the code we have. In other words, the code currently is perfect, if it works in one thread. Without a multi-threaded test you will never be able to reproduce the problem.

**Comment by emilianodellacasa** [comment]
@yegor256 Sincerely, I don't quite understand the whole issue, so I prefer to close this pull request and focus on other issues.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#312](https://github.com/zold-io/zold/issues/312) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@pbenety According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

No issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by ypshenychka** [comment]
@pbenety ping

**Comment by pbenety** [comment]
@ypshenychka I confirm,

**Comment by ypshenychka** [comment]
@pbenety thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Pull request closed without merging**
